# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Mark Leighton Fisher"
name: "Mark Leighton Fisher"
email: "markleightonfisher at gmail dot com"
description: >- # this means to ignore newlines until "baseurl:"
  Mark Leighton Fisher (that's me) is a software engineer and consultant,
  writer, and real estate investor. He also dabbles in music and
  cartooning as well as horseback riding.
twitter_username: MarkLFisher
github_username: markleightonfisher
minimal_mistakes_skin: contrast
site.locale: en-US
search: true
github: [metadata]

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Mark Leighton Fisher"
  avatar : "/assets/images/headshot-purdue-2013-82x82.jpeg"
  bio    : "Software engineer, writer, and real estate investor."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://markleightonfisher.github.io"
    - label: "CV"
      icon: "fas fa-fw fa-link"
      url: "CV.html"
    - label: "Perl Module Tools (pmtools)"
      icon: "fas fa-fw fa-link"
      url: "https://metacpan.org/pod/pmtools"
    - label: "Stupid Lucene Tricks"
      icon: "fas fa-fw fa-link"
      url: "/stupid-lucene-tricks/"
    - label: "Blog"
      icon: "fas fa-fw fa-link"
      url: "/posts/"
    - label: "Perl Blog"
      icon: "fas fa-fw fa-link"
      url: "http://blogs.perl.org/users/mark_leighton_fisher/"
    - label: "MetaCPAN"
      icon: "fas fa-fw fa-link"
      url: "https://metacpan.org/author/MLFISHER"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/markleightonfisher"
    - label: "GitHub for WebGUI"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pbmarklf"
    - label: "Stack Overflow user story"
      icon: "fas fa-fw fa-link"
      url: "https://stackoverflow.com/story/markleightonfisher"
    - label: "LinkedIn"
      icon: "fas fa-fw fa-link"
      url: "https://www.linkedin.com/in/mark-leighton-fisher/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/MarkLFisher"
    - label: "Some Other Links"
      icon: "fas fa-fw fa-link"
      url: "/some-other-links/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/MarkLFisher"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/markleightonfisher"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
